name: build

on: [push, create]

jobs:

  lint-and-test:

    name: Linting and Testing
    runs-on: ubuntu-latest

    env:
      CODECOV_TOKEN: '2c627fc7-525f-41fd-bc00-f5b7efae4eee'

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7.6'

    - name: Lint with flake8
      run: |
        pip install -r requirements/requirements-style.txt
        flake8

    - name: Test with pytest
      run: |
        pip install -r requirements/requirements-test.txt
        pytest --cov=interview_preparation_kit --cov-branch
        codecov --token=$CODECOV_TOKEN
