name: Python package

on: push

jobs:

  lint-and-test:

    name: Linting and Testing
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: 3.7.5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python $PYTHON_VERSION
      uses: actions/setup-python@v1
      with:
        python-version: $PYTHON_VERSION

    - name: Lint with flake8
      run: |
        pip install -r requirements/requirements-style.txt
        flake8

    - name: Test with pytest
      run: |
        pip install -r requirements/requirements-test.txt
        pytest --cov=interview_preparation_kit --cov-branch
